// ── Tỉnh / Thành phố 63 tỉnh ─────────────────────────────────────────────
export const PROVINCES = [
  { id: 'hcm',       name: 'Hồ Chí Minh' },
  { id: 'hn',        name: 'Hà Nội' },
  { id: 'dn',        name: 'Đà Nẵng' },
  { id: 'ct',        name: 'Cần Thơ' },
  { id: 'hp',        name: 'Hải Phòng' },
  { id: 'ag',        name: 'An Giang' },
  { id: 'brvt',      name: 'Bà Rịa - Vũng Tàu' },
  { id: 'bl',        name: 'Bạc Liêu' },
  { id: 'bg',        name: 'Bắc Giang' },
  { id: 'bk',        name: 'Bắc Kạn' },
  { id: 'bn',        name: 'Bắc Ninh' },
  { id: 'btre',      name: 'Bến Tre' },
  { id: 'bdinh',     name: 'Bình Định' },
  { id: 'bduong',    name: 'Bình Dương' },
  { id: 'bphuoc',    name: 'Bình Phước' },
  { id: 'bthuan',    name: 'Bình Thuận' },
  { id: 'cmau',      name: 'Cà Mau' },
  { id: 'cb',        name: 'Cao Bằng' },
  { id: 'dak',       name: 'Đắk Lắk' },
  { id: 'daknong',   name: 'Đắk Nông' },
  { id: 'dbien',     name: 'Điện Biên' },
  { id: 'dnai',      name: 'Đồng Nai' },
  { id: 'dtap',      name: 'Đồng Tháp' },
  { id: 'gialai',    name: 'Gia Lai' },
  { id: 'hagiang',   name: 'Hà Giang' },
  { id: 'hanam',     name: 'Hà Nam' },
  { id: 'hatinh',    name: 'Hà Tĩnh' },
  { id: 'haiduong',  name: 'Hải Dương' },
  { id: 'haugiang',  name: 'Hậu Giang' },
  { id: 'hoabinh',   name: 'Hòa Bình' },
  { id: 'hungyen',   name: 'Hưng Yên' },
  { id: 'khanhhoa',  name: 'Khánh Hòa' },
  { id: 'kiengiang', name: 'Kiên Giang' },
  { id: 'kontum',    name: 'Kon Tum' },
  { id: 'laichau',   name: 'Lai Châu' },
  { id: 'lamdong',   name: 'Lâm Đồng' },
  { id: 'langson',   name: 'Lạng Sơn' },
  { id: 'laocai',    name: 'Lào Cai' },
  { id: 'longan',    name: 'Long An' },
  { id: 'namdinh',   name: 'Nam Định' },
  { id: 'nghean',    name: 'Nghệ An' },
  { id: 'ninhbinh',  name: 'Ninh Bình' },
  { id: 'ninhthuan', name: 'Ninh Thuận' },
  { id: 'phutho',    name: 'Phú Thọ' },
  { id: 'phuyen',    name: 'Phú Yên' },
  { id: 'quangbinh', name: 'Quảng Bình' },
  { id: 'quangnam',  name: 'Quảng Nam' },
  { id: 'quangngai', name: 'Quảng Ngãi' },
  { id: 'quangninh', name: 'Quảng Ninh' },
  { id: 'quangtri',  name: 'Quảng Trị' },
  { id: 'socttrang', name: 'Sóc Trăng' },
  { id: 'sonla',     name: 'Sơn La' },
  { id: 'tayninh',   name: 'Tây Ninh' },
  { id: 'thaibinh',  name: 'Thái Bình' },
  { id: 'thainguyen',name: 'Thái Nguyên' },
  { id: 'thanhhoa',  name: 'Thanh Hóa' },
  { id: 'thuathienhue', name: 'Thừa Thiên Huế' },
  { id: 'tiengiang', name: 'Tiền Giang' },
  { id: 'travinh',   name: 'Trà Vinh' },
  { id: 'tuyenquang',name: 'Tuyên Quang' },
  { id: 'vinhlong',  name: 'Vĩnh Long' },
  { id: 'vinhphuc',  name: 'Vĩnh Phúc' },
  { id: 'yenbai',    name: 'Yên Bái' },
];

// ── Quận / Huyện đầy đủ 63 tỉnh ─────────────────────────────────────────
export const DISTRICTS = {
  hcm: ['Quận 1','Quận 3','Quận 4','Quận 5','Quận 6','Quận 7','Quận 8','Quận 10','Quận 11','Quận 12','Bình Chánh','Bình Tân','Bình Thạnh','Củ Chi','Cần Giờ','Gò Vấp','Hóc Môn','Nhà Bè','Phú Nhuận','Tân Bình','Tân Phú','Thủ Đức'],
  hn: ['Ba Đình','Ba Vì','Bắc Từ Liêm','Cầu Giấy','Chương Mỹ','Đan Phượng','Đông Anh','Đống Đa','Gia Lâm','Hà Đông','Hai Bà Trưng','Hoài Đức','Hoàn Kiếm','Hoàng Mai','Long Biên','Mê Linh','Mỹ Đức','Nam Từ Liêm','Phú Xuyên','Phúc Thọ','Quốc Oai','Sóc Sơn','Tây Hồ','Thạch Thất','Thanh Oai','Thanh Trì','Thanh Xuân','Thường Tín','Ứng Hòa'],
  dn: ['Cẩm Lệ','Hải Châu','Hòa Vang','Liên Chiểu','Ngũ Hành Sơn','Sơn Trà','Thanh Khê'],
  ct: ['Bình Thủy','Cái Răng','Cờ Đỏ','Ninh Kiều','Ô Môn','Phong Điền','Thốt Nốt','Thới Lai','Vĩnh Thạnh'],
  hp: ['An Dương','An Lão','Cát Hải','Dương Kinh','Đồ Sơn','Hải An','Hồng Bàng','Kiến An','Kiến Thụy','Lê Chân','Ngô Quyền','Thủy Nguyên','Tiên Lãng','Vĩnh Bảo'],
  ag: ['An Phú','Châu Đốc','Châu Phú','Châu Thành','Chợ Mới','Long Xuyên','Phú Tân','Tân Châu','Thoại Sơn','Tịnh Biên','Tri Tôn'],
  brvt: ['Bà Rịa','Châu Đức','Côn Đảo','Đất Đỏ','Long Điền','Tân Thành','Vũng Tàu','Xuyên Mộc'],
  bl: ['Đông Hải','Giá Rai','Hòa Bình','Hồng Dân','Phước Long','TP. Bạc Liêu','Vĩnh Lợi'],
  bg: ['Hiệp Hòa','Lạng Giang','Lục Nam','Lục Ngạn','Sơn Động','Tân Yên','TP. Bắc Giang','Việt Yên','Yên Dũng','Yên Thế'],
  bk: ['Ba Bể','Bạch Thông','Chợ Đồn','Chợ Mới','Na Rì','Ngân Sơn','TP. Bắc Kạn','Pác Nặm'],
  bn: ['Từ Sơn','Tiên Du','Yên Phong','Thuận Thành','Quế Võ','Lương Tài','Gia Bình','TP. Bắc Ninh'],
  btre: ['Ba Tri','Bình Đại','Châu Thành','Chợ Lách','Giồng Trôm','Mỏ Cày Bắc','Mỏ Cày Nam','TP. Bến Tre','Thạnh Phú'],
  bdinh: ['An Lão','An Nhơn','Hoài Ân','Hoài Nhơn','Phù Cát','Phù Mỹ','Quy Nhơn','Tây Sơn','Tuy Phước','Vân Canh','Vĩnh Thạnh'],
  bduong: ['Bến Cát','Bàu Bàng','Bắc Tân Uyên','Dĩ An','Dầu Tiếng','Phú Giáo','Tân Uyên','Thủ Dầu Một','Thuận An'],
  bphuoc: ['Bình Long','Bù Đăng','Bù Đốp','Bù Gia Mập','Chơn Thành','Đồng Phú','Hớn Quản','Lộc Ninh','Phú Riềng','Đồng Xoài'],
  bthuan: ['Bắc Bình','Đức Linh','Hàm Tân','Hàm Thuận Bắc','Hàm Thuận Nam','La Gi','Phan Thiết','Phú Quý','Tánh Linh','Tuy Phong'],
  cmau: ['Cái Nước','Đầm Dơi','Năm Căn','Ngọc Hiển','Phú Tân','TP. Cà Mau','Thới Bình','Trần Văn Thời','U Minh'],
  cb: ['Bảo Lạc','Bảo Lâm','Hà Quảng','Hạ Lang','Hòa An','Nguyên Bình','Phục Hòa','Quảng Uyên','Thạch An','TP. Cao Bằng','Thông Nông','Trà Lĩnh','Trùng Khánh'],
  dak: ['Buôn Đôn','Buôn Ma Thuột','Cư Kuin','Cư M\'gar','Ea H\'leo','Ea Kar','Ea Súp','Krông Ana','Krông Bông','Krông Búk','Krông Năng','Krông Pắc','Lắk','M\'Đrắk'],
  daknong: ['Cư Jút','Đắk G\'Long','Đắk Mil','Đắk R\'Lấp','Đắk Song','Gia Nghĩa','Krông Nô','Tuy Đức'],
  dbien: ['Điện Biên','Điện Biên Đông','Mường Ảng','Mường Chà','Mường Lay','Mường Nhé','Nậm Pồ','TP. Điện Biên Phủ','Tủa Chùa','Tuần Giáo'],
  dnai: ['Biên Hòa','Cẩm Mỹ','Định Quán','Long Khánh','Long Thành','Nhơn Trạch','Tân Phú','Thống Nhất','Trảng Bom','Vĩnh Cửu','Xuân Lộc'],
  dtap: ['Cao Lãnh','Châu Thành','Hồng Ngự','Lai Vung','Lấp Vò','Sa Đéc','Tam Nông','Tân Hồng','Tháp Mười','Thanh Bình','Tràm Chim'],
  gialai: ['An Khê','Ayun Pa','Chư Păh','Chư Prông','Chư Pưh','Chư Sê','Đăk Đoa','Đăk Pơ','Đức Cơ','Ia Grai','Ia Pa','K\'Bang','Kbang','Kon Chro','Mang Yang','Phú Thiện','Pleiku'],
  hagiang: ['Bắc Mê','Bắc Quang','Đồng Văn','Hoàng Su Phì','Mèo Vạc','Quản Bạ','Quang Bình','TP. Hà Giang','Vị Xuyên','Xín Mần','Yên Minh'],
  hanam: ['Bình Lục','Duy Tiên','Kim Bảng','Lý Nhân','Phủ Lý','Thanh Liêm'],
  hatinh: ['Cẩm Xuyên','Can Lộc','Đức Thọ','Hương Khê','Hương Sơn','Kỳ Anh','Lộc Hà','Nghi Xuân','TP. Hà Tĩnh','Thạch Hà','Vũ Quang'],
  haiduong: ['Bình Giang','Cẩm Giàng','Chí Linh','Gia Lộc','Kim Thành','Kinh Môn','Nam Sách','Ninh Giang','Thanh Hà','Thanh Miện','TP. Hải Dương','Tứ Kỳ'],
  haugiang: ['Châu Thành','Châu Thành A','Long Mỹ','Ngã Bảy','Phụng Hiệp','TP. Vị Thanh','Vị Thủy'],
  hoabinh: ['Cao Phong','Đà Bắc','Kim Bôi','Kỳ Sơn','Lac Sơn','Lạc Thủy','Lương Sơn','Mai Châu','Tân Lạc','TP. Hòa Bình','Yên Thủy'],
  hungyen: ['Ân Thi','Khoái Châu','Kim Động','Mỹ Hào','Phù Cừ','Tiên Lữ','TP. Hưng Yên','Văn Giang','Văn Lâm','Yên Mỹ'],
  khanhhoa: ['Cam Lâm','Cam Ranh','Diên Khánh','Khánh Sơn','Khánh Vĩnh','Nha Trang','Ninh Hòa','Vạn Ninh'],
  kiengiang: ['An Biên','An Minh','Châu Thành','Giang Thành','Giồng Riềng','Gò Quao','Hà Tiên','Hòn Đất','Kiên Hải','Kiên Lương','Phú Quốc','Rạch Giá','Tân Hiệp','U Minh Thượng','Vĩnh Thuận'],
  kontum: ['Đắk Glei','Đắk Hà','Đắk Tô','Ia H\'Drai','Kon Plông','Kon Rẫy','Ngọc Hồi','Sa Thầy','Tu Mơ Rông','TP. Kon Tum'],
  laichau: ['Mường Tè','Nậm Nhùn','Phong Thổ','Sìn Hồ','Tam Đường','Than Uyên','TP. Lai Châu','Tân Uyên'],
  lamdong: ['Bảo Lâm','Bảo Lộc','Cát Tiên','Đạ Huoai','Đạ Tẻh','Đam Rông','Di Linh','Đơn Dương','Đức Trọng','Lạc Dương','Lâm Hà','TP. Đà Lạt'],
  langson: ['Bắc Sơn','Bình Gia','Cao Lộc','Chi Lăng','Đình Lập','Hữu Lũng','Lộc Bình','TP. Lạng Sơn','Tràng Định','Văn Lãng','Văn Quan'],
  laocai: ['Bắc Hà','Bảo Thắng','Bảo Yên','Bát Xát','Mường Khương','Sa Pa','Si Ma Cai','TP. Lào Cai','Văn Bàn'],
  longan: ['Bến Lức','Cần Đước','Cần Giuộc','Châu Thành','Đức Hòa','Đức Huệ','Kiến Tường','Mộc Hóa','TP. Tân An','Tân Hưng','Tân Thạnh','Tân Trụ','Thạnh Hóa','Thủ Thừa','Vĩnh Hưng'],
  namdinh: ['Giao Thủy','Hải Hậu','Mỹ Lộc','Nam Trực','Nghĩa Hưng','TP. Nam Định','Trực Ninh','Vụ Bản','Xuân Trường','Ý Yên'],
  nghean: ['Anh Sơn','Con Cuông','Cửa Lò','Diễn Châu','Đô Lương','Hoàng Mai','Hưng Nguyên','Kỳ Sơn','Nam Đàn','Nghi Lộc','Nghĩa Đàn','Quế Phong','Quỳ Châu','Quỳ Hợp','Quỳnh Lưu','Tân Kỳ','Thái Hòa','Thanh Chương','Tương Dương','Vinh','Yên Thành'],
  ninhbinh: ['Gia Viễn','Hoa Lư','Kim Sơn','Nho Quan','Ninh Bình','Tam Điệp','Yên Khánh','Yên Mô'],
  ninhthuan: ['Bác Ái','Ninh Hải','Ninh Phước','Ninh Sơn','Phan Rang - Tháp Chàm','Thuận Bắc','Thuận Nam'],
  phutho: ['Cẩm Khê','Đoan Hùng','Hạ Hòa','Lâm Thao','Phù Ninh','Tam Nông','Tân Sơn','Thanh Ba','Thanh Sơn','Thanh Thủy','TP. Việt Trì','Yên Lập'],
  phuyen: ['Đồng Xuân','Phú Hòa','Sông Cầu','Sông Hinh','Tây Hòa','Tuy An','Tuy Hòa','Đông Hòa'],
  quangbinh: ['Bố Trạch','Đồng Hới','Lệ Thủy','Minh Hóa','Quảng Ninh','Quảng Trạch','Tuyên Hóa'],
  quangnam: ['Bắc Trà My','Cẩm Lệ (ĐN)','Duy Xuyên','Đại Lộc','Điện Bàn','Đông Giang','Hiệp Đức','Hội An','Nam Giang','Nam Trà My','Nông Sơn','Núi Thành','Phú Ninh','Phước Sơn','Quế Sơn','Tây Giang','Thăng Bình','Tiên Phước'],
  quangngai: ['Ba Tơ','Bình Sơn','Đức Phổ','Lý Sơn','Minh Long','Mộ Đức','Nghĩa Hành','Sơn Hà','Sơn Tây','Sơn Tịnh','TP. Quảng Ngãi','Trà Bồng','Tư Nghĩa'],
  quangninh: ['Ba Chẽ','Bình Liêu','Cẩm Phả','Cô Tô','Đầm Hà','Đông Triều','Hạ Long','Hải Hà','Hoành Bồ','Móng Cái','Quảng Yên','Tiên Yên','Uông Bí','Vân Đồn'],
  quangtri: ['Cam Lộ','Cồn Cỏ','Đakrông','Đông Hà','Gio Linh','Hải Lăng','Hướng Hóa','Quảng Trị','Triệu Phong','Vĩnh Linh'],
  socttrang: ['Châu Thành','Cù Lao Dung','Kế Sách','Long Phú','Mỹ Tú','Mỹ Xuyên','Ngã Năm','TP. Sóc Trăng','Thạnh Trị','Trần Đề','Vĩnh Châu'],
  sonla: ['Bắc Yên','Mai Sơn','Mộc Châu','Mường La','Phù Yên','Quỳnh Nhai','Sốp Cộp','TP. Sơn La','Thuận Châu','Vân Hồ','Yên Châu'],
  tayninh: ['Bến Cầu','Châu Thành','Dương Minh Châu','Gò Dầu','Hòa Thành','Tân Biên','Tân Châu','TP. Tây Ninh','Trảng Bàng'],
  thaibinh: ['Đông Hưng','Hưng Hà','Kiến Xương','Quỳnh Phụ','TP. Thái Bình','Thái Thụy','Tiền Hải','Vũ Thư'],
  thainguyen: ['Định Hóa','Đại Từ','Đồng Hỷ','Phổ Yên','Phú Bình','Phú Lương','Sông Công','TP. Thái Nguyên','Võ Nhai'],
  thanhhoa: ['Bá Thước','Bỉm Sơn','Cẩm Thủy','Đông Sơn','Hà Trung','Hậu Lộc','Hoằng Hóa','Lang Chánh','Mường Lát','Nga Sơn','Ngọc Lặc','Như Thanh','Như Xuân','Nông Cống','Quan Hóa','Quan Sơn','Quảng Xương','Sầm Sơn','Thạch Thành','Thiệu Hóa','Thọ Xuân','Thường Xuân','TP. Thanh Hóa','Triệu Sơn','Vĩnh Lộc','Yên Định'],
  thuathienhue: ['A Lưới','Hương Thủy','Hương Trà','Nam Đông','Phong Điền','Phú Lộc','Phú Vang','TP. Huế'],
  tiengiang: ['Cái Bè','Cai Lậy','Châu Thành','Chợ Gạo','Gò Công','Gò Công Đông','Gò Công Tây','Mỹ Tho','Tân Phú Đông','Tân Phước'],
  travinh: ['Càng Long','Cầu Kè','Cầu Ngang','Châu Thành','Duyên Hải','Tiểu Cần','TP. Trà Vinh','Trà Cú'],
  tuyenquang: ['Chiêm Hóa','Hàm Yên','Lâm Bình','Na Hang','Sơn Dương','TP. Tuyên Quang','Yên Sơn'],
  vinhlong: ['Bình Minh','Bình Tân','Long Hồ','Mang Thít','Tam Bình','TP. Vĩnh Long','Trà Ôn','Vũng Liêm'],
  vinhphuc: ['Bình Xuyên','Lập Thạch','Phúc Yên','Sông Lô','Tam Đảo','Tam Dương','Tam Sơn','TP. Vĩnh Yên','Vĩnh Tường','Yên Lạc'],
  yenbai: ['Lục Yên','Mù Cang Chải','Nghĩa Lộ','Trạm Tấu','Trấn Yên','TP. Yên Bái','Văn Chấn','Văn Yên','Yên Bình'],
};

// ── Cửa hàng mẫu ─────────────────────────────────────────────────────────
export const STORES = {
  'hcm-Quận 1': ['134 Nguyễn Thái Học, P.Phạm Ngũ Lão, Q.1','55B Trần Quang Khải, P.Tân Định, Q.1','157 Nguyễn Thị Minh Khai, P.Phạm Ngũ Lão, Q.1'],
  'hcm-Quận 3': ['254 Điện Biên Phủ, P.7, Q.3','381 Điện Biên Phủ, P.4, Q.3'],
  'hcm-Quận 4': ['200 Nguyễn Tất Thành, P.13, Q.4'],
  'hcm-Quận 5': ['234 Nguyễn Trãi, P.3, Q.5','88 Bình Tây, P.3, Q.5'],
  'hcm-Quận 6': ['678 Hồng Bàng, P.6, Q.6'],
  'hcm-Quận 7': ['850 Huỳnh Tấn Phát, P.Phú Mỹ, Q.7','SC VivoCity, 1058 Nguyễn Văn Linh, Q.7'],
  'hcm-Quận 8': ['274 Phạm Thế Hiển, P.4, Q.8'],
  'hcm-Quận 10': ['200 Tô Hiến Thành, P.14, Q.10','543 Sư Vạn Hạnh, P.13, Q.10'],
  'hcm-Quận 11': ['252 Lý Thường Kiệt, P.14, Q.11'],
  'hcm-Quận 12': ['142 Lê Văn Khương, P.Thới An, Q.12'],
  'hcm-Bình Thạnh': ['216 Đinh Bộ Lĩnh, P.26, Q.Bình Thạnh','563 Xô Viết Nghệ Tĩnh, P.26, Q.Bình Thạnh'],
  'hcm-Gò Vấp': ['1066 Quang Trung, P.12, Q.Gò Vấp'],
  'hcm-Tân Bình': ['449 Trường Chinh, P.14, Q.Tân Bình','153 Hoàng Văn Thụ, P.8, Q.Tân Bình'],
  'hcm-Tân Phú': ['560 Lũy Bán Bích, P.Hòa Thạnh, Q.Tân Phú'],
  'hcm-Bình Tân': ['1368 Kinh Dương Vương, P.An Lạc A, Q.Bình Tân'],
  'hcm-Thủ Đức': ['216 Võ Văn Ngân, P.Bình Thọ, TP.Thủ Đức','628 Kha Vạn Cân, P.Linh Đông, TP.Thủ Đức'],
  'hcm-Phú Nhuận': ['194 Phan Đình Phùng, P.2, Q.Phú Nhuận'],
  'hcm-Bình Chánh': ['217B5/7 An Phú Tây, Huyện Bình Chánh'],
  'hn-Hoàn Kiếm': ['47 Đinh Tiên Hoàng, P.Tràng Tiền, Q.Hoàn Kiếm','98 Hai Bà Trưng, Q.Hoàn Kiếm'],
  'hn-Đống Đa': ['20 Láng Hạ, Q.Đống Đa','214 Tôn Đức Thắng, Q.Đống Đa'],
  'hn-Cầu Giấy': ['272 Xuân Thủy, Q.Cầu Giấy','Indochina Plaza, 241 Xuân Thủy'],
  'hn-Thanh Xuân': ['462 Nguyễn Trãi, Q.Thanh Xuân','204 Nguyễn Tuân, Q.Thanh Xuân'],
  'hn-Hà Đông': ['63 Quang Trung, Q.Hà Đông'],
  'hn-Hai Bà Trưng': ['303 Bạch Mai, Q.Hai Bà Trưng'],
  'hn-Hoàng Mai': ['1 Giải Phóng, Q.Hoàng Mai'],
  'hn-Long Biên': ['200 Nguyễn Văn Cừ, Q.Long Biên'],
  'dn-Hải Châu': ['254 Hùng Vương, Q.Hải Châu','159 Lê Duẩn, Q.Hải Châu'],
  'dn-Thanh Khê': ['312 Điện Biên Phủ, Q.Thanh Khê'],
  'dn-Sơn Trà': ['36 Ngô Quyền, Q.Sơn Trà'],
  'dn-Liên Chiểu': ['259 Tôn Đức Thắng, Q.Liên Chiểu'],
  'ct-Ninh Kiều': ['116 Trần Hưng Đạo, Q.Ninh Kiều','240 Nguyễn Trãi, Q.Ninh Kiều'],
  'ct-Bình Thủy': ['67 Cách Mạng Tháng 8, Q.Bình Thủy'],
  'hp-Ngô Quyền': ['173 Cầu Đất, Q.Ngô Quyền'],
  'hp-Lê Chân': ['286 Tô Hiệu, Q.Lê Chân'],
  'hp-Hồng Bàng': ['52 Quang Trung, Q.Hồng Bàng'],
  'brvt-Vũng Tàu': ['05 Lê Lợi, TP.Vũng Tàu','12 Nam Kỳ Khởi Nghĩa, TP.Vũng Tàu'],
  'brvt-Bà Rịa': ['45 Phước Thắng, TP.Bà Rịa'],
  'bduong-Thủ Dầu Một': ['128 Đại lộ Bình Dương, TP.Thủ Dầu Một'],
  'bduong-Dĩ An': ['45 Tân Lập, TX.Dĩ An'],
  'dnai-Biên Hòa': ['179 Phạm Văn Thuận, TP.Biên Hòa','91 Đồng Khởi, TP.Biên Hòa'],
  'khanhhoa-Nha Trang': ['34 Thái Nguyên, TP.Nha Trang','86 Hoàng Hoa Thám, TP.Nha Trang'],
  'lamdong-TP. Đà Lạt': ['6 Hùng Vương, TP.Đà Lạt','76 Nguyễn Chí Thanh, TP.Đà Lạt'],
  'nghean-Vinh': ['66 Lê Lợi, TP.Vinh','152 Nguyễn Thị Minh Khai, TP.Vinh'],
  'thuathienhue-TP. Huế': ['9 Phạm Ngũ Lão, TP.Huế','100 Hùng Vương, TP.Huế'],
  'quangninh-Hạ Long': ['Vincom Bãi Cháy, TP.Hạ Long','12 Trần Phú, TP.Hạ Long'],
  'thanhhoa-TP. Thanh Hóa': ['24 Đại Lộ Lê Lợi, TP.Thanh Hóa'],
  'quangnam-Hội An': ['88 Bạch Đằng, TP.Hội An'],
  'kiengiang-Rạch Giá': ['10 Trần Phú, TP.Rạch Giá'],
  'kiengiang-Phú Quốc': ['35 Trần Hưng Đạo, Dương Đông, Phú Quốc'],
  'tiengiang-Mỹ Tho': ['28 Nam Kỳ Khởi Nghĩa, TP.Mỹ Tho'],
  'longan-TP. Tân An': ['20 Hùng Vương, TP.Tân An'],
};

export function getDistricts(provinceId) {
  return DISTRICTS[provinceId] || [];
}

export function getStores(provinceId, district) {
  if (!provinceId || !district) return [];
  const key = `${provinceId}-${district}`;
  // Return stored if exists, else generate generic store
  if (STORES[key]) return STORES[key];
  const provinceName = (PROVINCES.find(p => p.id === provinceId) || {}).name || '';
  return [`123 Đường Trung Tâm, ${district}, ${provinceName}`];
}
